










GET http://127.0.0.1:8000/api/products/
Content-Type: application/json


###


POST http://127.0.0.1:8000/api/products/create/
Content-Type: application/json

{
    "slug": "t-shirt",
    "name": "T-shirt",
    "price": 10
}

###


GET http://127.0.0.1:8000/api/products/t-shirt/
Content-Type: application/json


###


PUT http://127.0.0.1:8000/api/products/t-shirt/
Content-Type: application/json

{
    "slug": "hat",
    "name": "Hat",
    "price": 10
}

###

PATCH  http://127.0.0.1:8000/api/products/hat/
Content-Type: application/json

{
    "price": 8
}


###

DELETE  http://127.0.0.1:8000/api/products/hat/
Content-Type: application/json


###









